### ISSUE TITLE
.BIN output files?

### ISSUE THREAD

**Issue by K4KDR** [drmpeg/gr-dvbldpc#1]
Runs great - thanks for the effort!

Please forgive a novice, but what are the two .BIN output files?  What does one DO with them?

Thanks!

-Scott,  K4KDR

**Comment by drmpeg** [comment]
They are the original LDPC coded bitstream (ldpcorg.bin) and the error corrected bitstream (ldpc.bin). At the end of the run, you can see how well the error correction did by comparing the two files. In Linux:

cmp -l ldpcorg.bin ldpc.bin

For the test flow graph, you should get these results (the noise source always gets seeded the same way).

```
re@w6rz:~/xfer$ cmp -l ldpcorg.bin ldpc.bin
   60791   0   1
10428101   0   1
21249762   0   1
34130239   1   0
38225070   0   1
60053522   1   0
63102959   1   0
65181690   0   1
83638119   0   1
re@w6rz:~/xfer$ 
```

I set the amplitude of the noise source so that a few errors slip through to show that something is really happening. You can modify the noise source amplitude to see how that affects decoding. You can also change the code rate. Lower code rates (i.e., 1/2 is lower than 2/3) will correct more errors. Be sure to match the code rate selection in all the blocks (yes, it's a bit tedious).

**Comment by K4KDR** [comment]
Thanks a million for the explanation!

Interestingly, using all the default settings (except specifying file locations), I got different results:

```
k4kdr@:~/gr-dvbldpc/sample-file$ cmp -l ldpcorg.bin ldpc.bin
 9379006   0   1
14367507   1   0
14762809   1   0
16068432   1   0
19493404   1   0
22416885   1   0
32197692   0   1
40030378   1   0
44137275   1   0
45733689   0   1
56297909   1   0
59473525   1   0
60318071   0   1
74636384   0   1
80987873   0   1
80991084   0   1
```

**Comment by drmpeg** [comment]
It probably depends on which version of GNU Radio you're using. The fast noise source was changed fairly recently to use xoroshiro128 instead of rand(). I'm using 3.7.13.4 (the latest on the maint-3.7 branch).

https://en.wikipedia.org/wiki/Xoroshiro128%2B
